version: '3'

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
      MARIADB_DATABASE: 'sweatsocial'
    ports:
      - 3306:3306
    networks:
      app-network:
        ipv4_address: 10.0.0.110
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
volumes:
  db-data:
